<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jade"
    nsURI="http:///JadeDSAM.ecore" nsPrefix="br.pucrio.inf.les.genarch.extension.dsam.jade.model">
  <eClassifiers xsi:type="ecore:EClass" name="Jade">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agents" upperBound="-1"
        eType="#//Agent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" upperBound="-1"
        eType="#//Behavior" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" eSuperTypes="DSAMElementTypes.ecore#//GroupClass DSAMElementTypes.ecore#//VariableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" upperBound="-1"
        eType="#//Behavior" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" eSuperTypes="DSAMElementTypes.ecore#//GroupClass DSAMElementTypes.ecore#//VariableElement"/>
</ecore:EPackage>
