<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dsamtypes"
    nsURI="http:///DSAMElementTypes" nsPrefix="br.pucrio.inf.les.genarch.models.dsamtypes">
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="archName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassesImpl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedClasses" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AspectsImpl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedAspects" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationAspect"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilesImpl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedFiles" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationFile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplatesImpl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedTemplates" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationTemplate"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentsImpl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedComponents" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationComponent"
        derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FoldersImpl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedFolders" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationFolder"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FragmentsImpl" abstract="true">
    <eAnnotations source="propName" references="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedFragments" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationFragment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationImpl" abstract="true" eSuperTypes="#//ClassesImpl #//AspectsImpl">
    <eAnnotations source="anottationName"/>
  </eClassifiers>
</ecore:EPackage>
