<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dsamtypes"
    nsURI="http:///DSAMElementTypes" nsPrefix="br.pucrio.inf.les.genarch.models.dsamtypes">
  <eClassifiers xsi:type="ecore:EClass" name="DomainElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupRelationship" abstract="true" eSuperTypes="#//DomainElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DependenceRelationship" abstract="true"
      eSuperTypes="#//DomainElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="GroupClass" abstract="true" eSuperTypes="#//GroupRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupAspects" abstract="true" eSuperTypes="#//GroupRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspects" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationAspect"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupFiles" abstract="true" eSuperTypes="#//GroupRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationFile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupTemplates" abstract="true" eSuperTypes="#//GroupRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationTemplate"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupComponents" abstract="true" eSuperTypes="#//GroupRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationComponent"
        derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupFolders" abstract="true" eSuperTypes="#//GroupRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="folders" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationFolder"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupFragments" abstract="true" eSuperTypes="#//GroupRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationFragment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDependence" eSuperTypes="#//DependenceRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AspectDependence" eSuperTypes="#//DependenceRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspects" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationAspect"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileDependence" eSuperTypes="#//DependenceRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationFile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateDependence" eSuperTypes="#//DependenceRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationTemplate"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentDependence" eSuperTypes="#//DependenceRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationComponent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FolderDependence" eSuperTypes="#//DependenceRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="folders" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationFolder"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FragmentDependence" eSuperTypes="#//DependenceRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1"
        eType="ecore:EClass ImplementationMetaModel.ecore#//ImplementationFragment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableElement" eSuperTypes="#//DomainElement"/>
</ecore:EPackage>
