<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="spring"
    nsURI="http:///SpringDomainModel.ecore" nsPrefix="br.pucrio.inf.les.genarch.extension.dsam.spring.model">
  <eClassifiers xsi:type="ecore:EClass" name="Spring">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beans" lowerBound="1" upperBound="-1"
        eType="#//Bean" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bean" eSuperTypes="DSAMElementTypes.ecore#//GroupClass DSAMElementTypes.ecore#//VariableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" upperBound="-1"
        eType="#//BeanVariant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
        eType="#//Interface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeanVariant" eSuperTypes="DSAMElementTypes.ecore#//GroupClass DSAMElementTypes.ecore#//GroupFragments DSAMElementTypes.ecore#//VariableElement">
    <eAnnotations source="XML">
      <details key="prop" value="Bean"/>
      <details key="attr" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//BeanReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeanReference" eSuperTypes="DSAMElementTypes.ecore#//IntraDependence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="DSAMElementTypes.ecore#//GroupClass"/>
</ecore:EPackage>
