
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 28 15:48:39 GMT-03:00 2008
//----------------------------------------------------

package br.pucrio.inf.les.genarch.core.logic.model.expressions.parse;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RPAREN = 3;
  public static final int NOT = 6;
  public static final int AND = 5;
  public static final int error = 1;
  public static final int LPAREN = 2;
  public static final int OR = 4;
  public static final int EOF = 0;
  public static final int FEATURE = 7;
}

